### PR TITLE
Use subdir when the cache directory is defined through an ENV variable

### PR DESCRIPTION
**Pull request by armish**
Addresses https://github.com/hammerlab/pyensembl/issues/167

---

This change is [Reviewable](https://reviewable.io/reviews/hammerlab/datacache/28)

### CODE REVIEW

**Comment by iskandr** [comment]
@armish I'm not sure I understand the new semantics. Shouldn't an environment defined path totally by-pass `datacache`'s cache dir?

**Comment by armish** [comment]
@iskandr: I think it should only by-pass datacache's default path to the parent cache dir. If the developer is specifically passing a `subdir` paremeter to the function, I think `datacache` should respect that, create the parent cache directory from the env and return the path to the subdir instead of just returning what is set by the environment variable.

Otherwise, `datacache` will just flatten whatever directory structure the developer has in mind if/when the user overrides the maindir via this environment variable. `pyensembl` is not directly affected from this behaviour as we don't expect to have name conflicts for the files to be cached, but one can easily imagine a scenario where the developer utilizes the subdir/path strategy to differentiate between different versions/init.s of a particular cache.

**Comment by iskandr** [comment]
On the other hand, it's a little weird to always append "datacache" the path we get from the env. 

Suggestion:
If we're building a path starting from an environment key, then ignore an empty `subdir` argument. If we're using `appdirs` then an empty `subdir` defaults to "datacache" (to avoid polluting `~/Library/Caches`).

**Comment by iskandr** [comment]
@armish Want me to revive this PR by rebasing off the new master?

**Comment by armish** [comment]
Sure - happy to tackle it by myself if you don't have the time.

**Comment by iskandr** [comment]
@armish OK, made it so that the subdir defaults to "datacache" only if envkey is undefined or empty.

**Pull request merged**
