### PR TITLE
Create database with multiple tables

### PR DESCRIPTION
**Pull request by iskandr**
This is a refactoring of the messy `db` module. I've split up a tangle of interwoven helper functions inside of one module into a slightly less tangled collection of modules. 

Now we have:
- `Database`, which wraps a `sqlite3` connection and contains all the helper methods for initializing and filling a database. 
- `DatabaseTable`, which contains all the previously scattered metadata related to tables we would like to construct (name, function to lazily construct row tuples, indices, primary key, &c). 
- `database_types` is a module devoted solely to converting from numerical & string types to names of `sqlite3` column types

I've added more unit tests to cover the obvious code paths through this rat's nest. In the near term we should add coverage reporting to tell more obviously what additional tests are needed. In the longer run, I'm open to switching to SqlAlchemy, since that seems to be what I'm slowly reimplementing here. 

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/datacache/16)

### CODE REVIEW

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/datacache/16)

Reviewed files:
- datacache/__init__.py @ r2
- datacache/cache.py @ r3
- datacache/common.py @ r2
- datacache/database.py @ r2
- datacache/database_helpers.py @ r2
- datacache/database_table.py @ r2
- datacache/database_types.py @ r2
- datacache/db.py @ r1
- datacache/download.py @ r2
- datacache/fasta.py @ r1
- requirements.txt @ r1
- setup.py @ r2
- test/test_database.py @ r1
- test/test_database_objects.py @ r2
- test/test_database_types.py @ r3
- test/test_db_from_dataframes.py @ r2
- test/test_download.py @ r2
- test/test_fasta_db.py @ r2
- test/test_fasta_dict.py @ r2
- test/test_names.py @ r2





---

<sup>**[datacache/database.py, line 53 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjSg5LV__2Kx6jBNTlw)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L53)):</sup>
This double query (table_names followed by execute_sql) felt silly, but then I Googled for better ways and am not seeing great options.

---

<sup>**[datacache/database.py, line 67 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUrQbQSZNztafuzdJz)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L67)):</sup>
Seems problematic that if table_names is 20 names, you'll run 20 + 1 table_names queries? Can you cache the table_names result, or just have a separate SQL query for has_tables?

---

<sup>**[datacache/database.py, line 75 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUsy2JPBUIFl6e26tA)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L75)):</sup>
Why is METADATA_COLUMN_NAME not called METADATA_TABLE_NAME?

---

<sup>**[datacache/database.py, line 88 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUu64THnI370uEGzVB)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L88)):</sup>
Seems confusing to me that _set_version, which I'd imagine alters the version in the METADATA table, actually creates the table too?

---

<sup>**[datacache/database.py, line 106 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUwrYI8PYzW1CxQnru)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L106)):</sup>
It might be helpful to clarify, in the comments, which methods commit and which don't. (E.g. "This does not commit.")

---

<sup>**[datacache/database.py, line 126 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUwTCphoBe_KLaWdT2)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L126)):</sup>
This part does feel fairly error-prone relatively to using sqlalchemy.

---

<sup>**[datacache/database.py, line 143 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUxV7CVuJJg2sgTsNs)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L143)):</sup>
Again, this double-querying makes me nervous, and also feels unnecessary when _fill_table is used right after _create_table.

---

<sup>**[datacache/database.py, line 180 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUzmViUxSOt6yrp8UY)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L180)):</sup>
I think _create_index and _create_indices could use some docstrings to describe what an index_column_set is and what the indices parameter is an iterable of.

---

<sup>**[datacache/database_helpers.py, line 42 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjV-GOtMofRCshSnBo9)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L42)):</sup>
Two queries right here? Feels silly.

---

<sup>**[datacache/database_helpers.py, line 43 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjV-OZKlYanXsDk38BZ)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L43)):</sup>
So what happens if we create this DB connection and don't return it? When does it get closed?

---

<sup>**[datacache/database_helpers.py, line 76 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjV8WLTAjA0m6WSFaMu)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L76)):</sup>
Why not juse use require_int here?

---

<sup>**[datacache/database_helpers.py, line 84 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjV8JgbEVBRRaFmyhPQ)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L84)):</sup>
I've been consciously avoiding nitpicking comments, though this one actually confused me: "assuming it's complete" had me thinking that you were doing a completeness check.

---

<sup>**[datacache/database_helpers.py, line 96 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjV9cR6y2NbfvkG1jEV)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L96)):</sup>
Querying for table_names twice? In general, SQLAlchemy could probably help with ensuring that the metadata is cached instead of re-queried.

---

<sup>**[datacache/database_helpers.py, line 106 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjV9xfkmtN2Bdm8k8o4)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L106)):</sup>
This except with no Exception class makes me nervous. Are there specific exceptions you're expecting?

---

<sup>**[datacache/database_helpers.py, line 112 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVAT1Zu4Ns7sQQyc9O)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L112)):</sup>
Thinking out loud: I guess you don't need to wrap remove() in a try since we're already raising anyway.

---

<sup>**[datacache/database_helpers.py, line 137 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVC9Fqiqru5H-PB8sg)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L137)):</sup>
How does this relate to pyensembl's usage of pyfaidx?

---

<sup>**[datacache/database_helpers.py, line 152 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVDT-Auy1Bu93nxcq_)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L152)):</sup>
I didn't have context for this until I saw its usage in fetch_csv_db. I also found build_path vs. _construct_db_filename confusing. Can you add some context to the docstring?

---

<sup>**[datacache/database_helpers.py, line 168 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVCqBCPpmvE9B3hSJV)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L168)):</sup>
Why does version default to 1, vs. `if not version: return 0` above? Should version even have a default?

---

<sup>**[datacache/database_helpers.py, line 236 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVDolJ76I659oaJdl1)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L236)):</sup>
When is this used?

---

<sup>**[datacache/database_table.py, line 55 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVEGdXOn1rMR9aeb14)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_table.py#L55)):</sup>
Are there other characters that a DataFrame supports but sqlite wouldn't?

---

<sup>**[datacache/database_types.py, line 22 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVGS3TA34ZAxxUWSmr)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_types.py#L22)):</sup>
Why not just map from python types to DB types? Wouldn't that make for a shorter/simpler dictionary?

---

<sup>**[datacache/database_types.py, line 51 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVHxKOEu6GGyCizYls)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_types.py#L51)):</sup>
I was fairly confused by some of this code, because I couldn't figure out if you were trying to convert from NumPy types to Python types, or from Python types to NumPy types, or...

Anyway, it looks like you end up with NumPy type names like 'int16' as well as python type names like 'int'?

---

<sup>**[datacache/database_types.py, line 56 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVIJ7O_a1rLOd3sklw)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_types.py#L56)):</sup>
It wasn't obvious to me that np.typeDict was a map from np type names to np types. Calling everything a python_type made that even more unclear to me.

---

<sup>**[datacache/database_types.py, line 71 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVJbc-XQeH9rNzy0eg)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_types.py#L71)):</sup>
Yikes. I hope there's a cleaner way to do some of this, though no ideas at the moment.

---

<sup>**[requirements.txt, line 7 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVKdSZqqxUsgsB8BpB)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/requirements.txt#L7)):</sup>
Replace nose2/version with nose/version?

Also, >= vs. == is a question I've had on my mind for requirements. Curious to get your thoughts.

---

<sup>**[setup.py, line 29 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVLAFpebueNozFFoyP)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/setup.py#L29)):</sup>
It's a bummer that all these changes have to be ported to lots of different repos. I wonder if it's worth centralizing these helpers into a shared repo.

---

<sup>**[setup.py, line 41 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVLHzcOVNaD4IcewWw)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/setup.py#L41)):</sup>
See what I did with pyensembl, based on a StackOverflow answer that you actually linked to :)

https://github.com/hammerlab/pyensembl/blob/travis/setup.py

```
requires_list = []
try:
    from pip.req import parse_requirements
    parsed_reqs = parse_requirements('requirements.txt')
    requires_list = [str(req.req) for req in parsed_reqs]
except ImportError:
    print("Please install pip before proceeding")
```

Perhaps this is another vote for centralizing some of this boilerplate.

---

<sup>**[test/test_database_objects.py, line 49 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVLqYJhKM2dgja-jIP)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/test/test_database_objects.py#L49)):</sup>
Unnecessary print?

---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/datacache/16)







---

<sup>**[datacache/database.py, line 53 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjSg5LV__2Kx6jBNTlw)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L53)):</sup>
Let me know if you think of a clearer way to do it. 

---

<sup>**[datacache/database.py, line 67 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUrQbQSZNztafuzdJz)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L67)):</sup>
What if you cache the table names and then someone modifies the database? This code is nice in that works regardless of state changes. It's also pretty clear what's going on. Also x2: I'm not sold on the need to speed it up: it's O(n) in the number of database tables...but so is the construction of the database (with much more significant constant factors).  

---

<sup>**[datacache/database.py, line 75 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUsy2JPBUIFl6e26tA)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L75)):</sup>
Great question, I have no idea.  (fixed)

---

<sup>**[datacache/database.py, line 88 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUu64THnI370uEGzVB)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L88)):</sup>
I renamed it to `_finalize_database`. How does that sound?

---

<sup>**[datacache/database.py, line 106 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUwrYI8PYzW1CxQnru)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L106)):</sup>
I added a comment to the class docstring since nothing commits other than close() and create()

---

<sup>**[datacache/database.py, line 126 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUwTCphoBe_KLaWdT2)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L126)):</sup>
Strangely, I think it's been the least problematic part of datacache. But I agree that it looks like it's waiting for a disaster.

---

<sup>**[datacache/database.py, line 143 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUxV7CVuJJg2sgTsNs)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L143)):</sup>
I'm going to challenge you to benchmark this one, I don't think that the number of small database queries at creation time matters much. And even if the error checking is currently redundant, who knows how we might accidentally use this method in the future? 

---

<sup>**[datacache/database.py, line 180 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUzmViUxSOt6yrp8UY)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L180)):</sup>
Added some docstrings and got rid of the index_number param.

---

<sup>**[datacache/database_helpers.py, line 42 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjV-GOtMofRCshSnBo9)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L42)):</sup>
```
In [5]: timeit db.version()
100000 loops, best of 3: 13.6 µs per loop
```

---

<sup>**[datacache/database_helpers.py, line 43 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjV-OZKlYanXsDk38BZ)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L43)):</sup>
It's up to the caller to close it if they want. But leaving open sqlite3 connections seems to have little consequence. 

---

<sup>**[datacache/database_helpers.py, line 76 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjV8WLTAjA0m6WSFaMu)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L76)):</sup>
Good call, this is before typechecks

---

<sup>**[datacache/database_helpers.py, line 84 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjV8JgbEVBRRaFmyhPQ)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L84)):</sup>
I phrased it a little clearer

---

<sup>**[datacache/database_helpers.py, line 96 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjV9cR6y2NbfvkG1jEV)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L96)):</sup>
This is only happening at database creation time when the runtime is totally dominated by inserting hundreds of millions of tuples per table into the database. I agree that if we were releasing this as a standalone database wrapper then all these `table_names()` queries might need to be faster, but for now I think they add up about 10ms of clock time. 

---

<sup>**[datacache/database_helpers.py, line 106 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjV9xfkmtN2Bdm8k8o4)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L106)):</sup>
Nope, if anything at all goes wrong we delete the database and then propagate the exception forward. 

---

<sup>**[datacache/database_helpers.py, line 112 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVAT1Zu4Ns7sQQyc9O)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L112)):</sup>
The file got created outside the `try` block, so it's guaranteed to exist. I guess it's possible that some totally external process deleted it from under our nose, but I think that indicates much more significant problems on a system. 

This comment did make me rethink the correctness of always deleting the file: what if the user is creating the file external to this call and doesn't expect it to get deleted upon error? I changed the logic to only delete files which didn't exist before the call. 

---

<sup>**[datacache/database_helpers.py, line 137 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVC9Fqiqru5H-PB8sg)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L137)):</sup>
I believe this creates an in-memory index but doesn't use or create an on-disk .fai file, whereas pyfaidx will reuse the index it's created. 

---

<sup>**[datacache/database_helpers.py, line 152 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVDT-Auy1Bu93nxcq_)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L152)):</sup>
Gave this a better name and longer docstring

---

<sup>**[datacache/database_helpers.py, line 168 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVCqBCPpmvE9B3hSJV)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L168)):</sup>
Lots of uses don't assume you're ever going to change the schema (e.g. creating a database from some fixed CSV layout or fasta file), so it's tedious to have to specify a version then. It's really around as an option for when you are crafting the schema yourself and might need to invalidate an old choice. 

Version defaults to 1 out of spite toward Edsgar Dijkstra. 

---

<sup>**[datacache/database_helpers.py, line 236 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVDolJ76I659oaJdl1)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L236)):</sup>
I was using it when I started writing epitopes (which got renamed to pepdata) but didn't really need it. Do you think it's fine to just delete this function? A theoretical user can just fetch the csv, parse it as a DataFrame and then use the DataFrame database helpers to make a db. 

---

<sup>**[datacache/database_table.py, line 55 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVEGdXOn1rMR9aeb14)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_table.py#L55)):</sup>
Good point, there are actually lots if we write the queries with naked table and column names. Made an issue for this: https://github.com/hammerlab/datacache/issues/17

---

<sup>**[datacache/database_types.py, line 22 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVGS3TA34ZAxxUWSmr)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_types.py#L22)):</sup>
How would you get to to `int` from `dtype('int8')`? 

---

<sup>**[datacache/database_types.py, line 51 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVHxKOEu6GGyCizYls)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_types.py#L51)):</sup>
Yep, since you might be converting the columns of a dataframe, a NumPy array, or regular old Python objects (with ordinary types). I didn't create this crazy system of runtime type representations! 

---

<sup>**[datacache/database_types.py, line 56 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVIJ7O_a1rLOd3sklw)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_types.py#L56)):</sup>
I added a little more to the comment, but overall this code is hard to make clear since it's trying to handle a bunch of confusing possibilities. 

---

<sup>**[requirements.txt, line 7 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVKdSZqqxUsgsB8BpB)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/requirements.txt#L7)):</sup>
I think >= is preferable until we encounter a library update that breaks compatibility. Is it possible to specify version ranges?

---

<sup>**[setup.py, line 29 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVLAFpebueNozFFoyP)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/setup.py#L29)):</sup>
Yeah, it kills me a little to copy this stuff around. 

---

<sup>**[setup.py, line 41 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVLHzcOVNaD4IcewWw)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/setup.py#L41)):</sup>
I saw one of the pip devs asking someone *not* to do this since they treat this as an internal functions whose API changes. See: https://github.com/machinalis/iepy/issues/63

---

<sup>**[test/test_database_objects.py, line 49 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVLqYJhKM2dgja-jIP)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/test/test_database_objects.py#L49)):</sup>
Removed

---

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/datacache/16)







---

<sup>**[datacache/database.py, line 70 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUrQbQSZNztafuzdJz)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L70)):</sup>
I didn't realize I had commented on the multi-querying so many times! I really hammered that issue home. Anyway, I wasn't really thinking about speed: the notion of unnecessary multi-querying just offended some part of my view of the world, and I felt like a caller of has_tables would be surprised to find out about 20 SQL calls (regardless of speed). And I just don't like surprises.

(Also, if we ever wanted these DB calls to be network roundtrips to some DB server...)

That said, I'm fine with leaving it as is for the time being.

---

<sup>**[datacache/database.py, line 91 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjUu64THnI370uEGzVB)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database.py#L91)):</sup>
My bad for not suggesting a name! I need to work on the proactive comments thing :)

That sounds good.

---

<sup>**[datacache/database_helpers.py, line 43 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjV-OZKlYanXsDk38BZ)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L43)):</sup>
I was thinking more about the situation where a connection is created but None is returned, making it impossible for the caller to close it. And am also thinking about keeping the code safe for non-sqlite3 usage. Anyway, just thinking out loud.

---

<sup>**[datacache/database_helpers.py, line 236 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVDolJ76I659oaJdl1)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L236)):</sup>
Yeah, reading a CSV into a DataFrame sounds super simple and this feels unnecessary.

---

<sup>**[datacache/database_types.py, line 22 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVGS3TA34ZAxxUWSmr)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_types.py#L22)):</sup>
I thought there'd be a way, but certainly haven't found it yet :)

---

<sup>**[requirements.txt, line 7 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVKdSZqqxUsgsB8BpB)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/requirements.txt#L7)):</sup>
Looks like ranges are possible: http://stackoverflow.com/questions/11472810/how-to-specify-version-ranges-in-install-requires-setuptools-distribute

I have no strong feelings on this at the moment. Just was curious to get your thoughts.

---

<sup>**[setup.py, line 41 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVLHzcOVNaD4IcewWw)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/setup.py#L41)):</sup>
Yikes. Good to know!

---

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/datacache/16)



---

Looks good to me!

---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/datacache/16)







---

<sup>**[datacache/database_helpers.py, line 44 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjV-OZKlYanXsDk38BZ)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L44)):</sup>
I think if we ever move beyond sqlite3 then we definitely should worry about this stuff more. I guess an explicit `else` branch with `db.connection.close()` would be fine, but I'll save that til we scale up :-)

---

<sup>**[datacache/database_helpers.py, line 240 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVDolJ76I659oaJdl1)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_helpers.py#L240)):</sup>
Made an issue: https://github.com/hammerlab/datacache/issues/18

---

<sup>**[datacache/database_types.py, line 20 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVGS3TA34ZAxxUWSmr)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/datacache/database_types.py#L20)):</sup>
I looked for a while, though I'm positive it must exist somewhere. 

---

<sup>**[requirements.txt, line 7 \[r3\]](https://reviewable.io:443/reviews/hammerlab/datacache/16#-JjVKdSZqqxUsgsB8BpB)** ([raw file](https://github.com/hammerlab/datacache/blob/faee856dc898892398a91d5fcd83335454ae58a2/requirements.txt#L7)):</sup>
I think we should just leave `>=` for now and revisit this if/when we run into trouble. Otherwise, I'm not sure what upperbound to put on each package. If we just limit it to the current max version then we'll be forced to update this file every time any of our dependencies gets a new version out.

---

**Pull request merged**
